# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b57ba1a8ea8e38fd914f06054f2af3613a983a7e8668d0f0df462668fced2400c3aa13fc21b6ad88e55ed4c2bfd38040d0d75f68436d1691764060747ac074b

test:
  secret_key_base: d1052f02242bf06c27d0cbd8477391b73ff04c702327408356a85d55f0db5ca6aadde6a3fd1d31d10ea41526cc114a280e9556c30b4117fbdd345ec9cea9d226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
