# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4aa4a731a4accdc43dc430f9cea59c502b2c7c04a6db70ef87cc0e7e46f8af435084a40cbf7734ac1774be4f61b26e5923b4e2ae9fe02f9d3a53c885aa79dec

test:
  secret_key_base: c3f567c9e7ed6db0ae623c15ff53bf8fb2fa716b15a21ce31b10ba7984698be541c8a5bf46b630a7343caae432b1b1b967ac2114bd78d16af91f247417946a49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
