# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50c448d0d1caff890959e419c9dc256223bc4bc2e64e1a1d3b5a375ed685a238b0171e8ac74d38816be06f4af134cc52fbf5cd272cf8a8541329cc5070887bb8

test:
  secret_key_base: 9d75299a98ba9c377a40fe522ef3349b0ce79fe650a2a8d9a586ae10950e06353a985b3a0f35ecb65d20b36dec08c42abd0e1a77d83c930846c9559fc99c6555

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
